addons: 
  chrome: stable
before_script: 
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
bundler_args: "--jobs=2"
cache: bundler
language: ruby
rvm: 
  - "2.6.3"
script: 
  - "bundle install"
  - "bundle exec rails webpacker:install "
  - "bundle exec rails webpacker:compile"
  - "bundle exec rspec"
